spring:
  application:
    name: exam

  datasource:
    url: jdbc:mysql://localhost:3306/exam
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    show-sql: false
  flyway:
    enabled: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 50MB
      max-request-size: 100MB

upload:
  path: "src/main/resources/static/images/"
